name: action

on: workflow_dispatch

jobs:
  ikuuu_sign:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/cat163/daily_tasks
          cd daily_tasks
      - name: install dependencies
        run: | 
          pip install pytest
          pip install requests
          pip install InsecureRequestWarning
      - name: run pytest
        run: pytest
