name: action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai


jobs:
  ikuuu_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests 
          pip3 install urllib3
      - name: Run
        env:
          USER_EMAIL: ${{ secrets.QQ_3502913960 }}
          USER_PASSWORD: ${{ secrets.QQ_3502913960_PWD_IKUUU }}
          GMAIL_SHUFFLING36: ${{ secrets.GMAIL_SHUFFLING36 }}
          GMAIL_SHUFFLING36_PWD_IKUUU: ${{ secrets.GMAIL_SHUFFLING36_PWD_IKUUU }}
          QQ_3502913960: ${{ secrets.QQ_1615703120 }}
          QQ_1615703120_PWD_IKUUU: ${{ secrets.QQ_1615703120 }}
        run: python3 ./ikuuu_sign.py
      - name: Show the timezone
        run: |
          echo "The timezone is $TZ"
          date
      
