name: action

on: workflow_dispatch

jobs:
  ikuuu_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests 
          pip3 install urllib3
      - name: Run
        run: python3 ./ikuuu_sign.py
      
